INSERT INTO metricas (met_sigla, met_descricao, met_breve_descricao)
VALUES
('M02', 'Tamanho total da parte de software das empresas', 'Tamanho da área de software'),
('M03', 'Benefícios obtidos por implementar/Melhorias que foram percebidas com a implementação', 'Benefícios/Melhorias'),
('M04', 'Qual Metodologia Ágil é mais implementada/seguida?', 'Metodologia mais implementada'),
('M05', 'Quantos anos a empresa têm praticado/implementado a agilidade', 'Tempo que a empresa pratica'),
('M06', 'Motivos mais importantes para implementar as metodologias ágeis', 'Motivos para implementar'),
('M08', 'Maiores preocupações sobre a implementação de metodologias ágeis', 'Preocupações'),
('M09', 'Barreiras para adotar e aumentar a implementação da agilidade em sua empresa', 'Barreiras para adotar e expandir'),
('M11', 'Quantos anos você pessoalmente (respondente) tem praticado a agilidade?', 'Tempo que o funcionário pratica'),
('M12', 'Cargo atual', 'Cargo atual'),
('M14', 'Tem algum time ágil distribuído que utiliza agilidade em mais de uma localização?', 'Times distribuídos'),
('M15', 'Quais práticas/técnicas você implementa nos métodos ágeis?', 'Práticas implementadas'),
('M16', 'Quais ferramentas específicas você utiliza (Agile project management tools)', 'Ferramentas específicas'),
('M18', 'Principal causa dos projetos ágeis que foram considerados malsucedidos', 'Causa dos projetos malsucedidos'),
('M24', 'Sua empresa já adotou metodologias ágeis em alguma parte da área de desenvolvimento de software?', 'Adoção da Agilidade pela empresa'),
('M26', 'Quais ferramentas ágeis você utiliza atualmente?', 'Ferramentas ágeis utilizadas'),
('M26', 'Quais ferramentas ágeis você planeja utilizar nos próximos 12 meses?', 'Ferramentas ágeis que planeja utilizar'),
('M36', 'Tamanho total da organização', 'Tamanho total da organização'),
('M37', 'Indústrias nas quais os respondentes trabalham', 'Indústrias'),
('M38', 'Porcentagem de times que utilizam metodologias ágeis', 'Porcentagens de times'),
('M39', 'Fases e maturidade da adoção de metodologias ágeis', 'Fases e Maturidade'),
('M40', 'Como o sucesso das iniciativas ágeis é medido/avaliado?', 'Como o sucesso das iniciativas ágeis é medido'),
('M41', 'No dia a dia, como o sucesso da implementação da agilidade é medido?', 'Como o sucesso da implementação é medido'),
('M42', 'Métodos e abordagens que são utilizados para auxiliar o escalonamento da agilidade', 'Métodos para o escalonamento'),
('M44', 'Práticas de engenharia empregadas', 'Práticas de engenharia empregadas'),
('M45', 'A organização possui ou planeja implementar iniciativas de DevOps?', 'DevOps'),
('M46', 'Importância da transformação de DevOps para a organização', 'Importância do DevOps'),
('M47', 'Como o sucesso das iniciativas de DevOps é medido?', 'Como o sucesso do DevOps é medido');