INSERT INTO submetricas (sub_descricao, fk_Metricas_met_id) 
VALUES
# M02 preciso checar a questão da equivalência entre os intervalos
('< 100', 1),
('101 - 1000', 1),
('1001 - 5000', 1),
('> 5001', 1),
# M03
('Ability to manage changing priorities', 2),
('Increased productivity', 2),
('Improved team morale', 2),
('Faster time to market', 2),
('Enhanced software quality', 2),
('Accelerated time-to-market', 2),
('Better alignment between it & business objectives', 2),
('Reduced software defects', 2),
('Project cost reduction', 2),
('Improved project visibility', 2),
('Manage distributed teams', 2),
('Better delivery predictability', 2),
('Improve/increase engineering discipline', 2),
('Enhance software mantainability/extensibility', 2),
('Reduced project risk', 2),
('Simplify development process', 2),
# M04
('Scrum', 3),
('Custom Hybrid', 3),
('Kanban', 3),
('Scrumban', 3),
('Iterative Development', 3),
('Scrum/XP Hybrid', 3),
('Lean Startup', 3),
('XP', 3),
('Spotify Model', 3),
('Lean', 3),
('Feature Driven Development (FDD)', 3),
('DSDM/Atern', 3),
('AgileUP', 3),
('Agile Modeling', 3),
('OpenUP', 3),
('Crystal', 3),
("Don't know/Other", 3),
("Don't know", 3),
('Other', 3),
# M05
('Average', 4),
('Not practicing agile', 4),
('< 1 year', 4),
('1 - 2 years', 4),
('2 - 5 years', 4),
('> 5 years', 4),
("Don't know", 4),
# M06
('Manage changing priorities', 5),
('Increase productivity', 5),
('Enhance software quality', 5),
('Accelerate time to market', 5),
('Alignment  between IT and Business needs', 5),
('Reduce project risk', 5),
('Improve project visibility', 5),
('Simplify development process', 5),
('Improve engineering discipline', 5),
('Reduce cost', 5),
('Enhance software Maintainability/Extensibility', 5),
('Improve team morale', 5),
('Manage distributed teams', 5),
('Enhance delivery predictability', 5),
('Better respond to volatile market conditions', 5),
('Other', 5),
# M08
('Lack of up-front planning', 6),
('Lack of documentation', 6),
('Loss of management control', 6),
('Lack of predictability', 6),
('Lack of engineering discipline', 6),
('Inability to scale', 6),
('Management opposed to change', 6),
('Development team opposed to change', 6),
('Quality of engineering talent', 6),
('Regulatory compliance', 6),
('Reduced software quality', 6),
('No concerns', 6),
('Other', 6),
# M09
('Not enough knowledge/skills/experience about Agile', 7),
('General resistance to change', 7),
('Customer collaboration', 7),
('Inadequate management support', 7),
('Project complexity or size', 7),
('Organization boundaries', 7),
('Ability to change organizational culture', 7),
('Confidence in ability to scale Agile methods', 7),
('Perceived time to transition', 7),
('Trying to fit agile elements into a non-agile frameworks', 7),
('Pre-existing rigid/waterfall framework', 7),
('Management concerns about lack of upfront planning', 7),
('Concerns about a loss of management control', 7),
('Concerns about the ability to scale Agile', 7),
('Development team support', 7),
('Budget constraints', 7),
('Regulatory compliance and governance', 7),
('Lack of business owner availability', 7),
('Organizational culture at odds with agile values', 7),
('Insufficient training and education', 7),
('Pervasiveness of traditional development methods', 7),
('Inconsistent agile practices and process across teams', 7),
('Fragmented tooling, data, and measurements', 7),
('Minimal collaboration and knowledge sharing', 7),
('Not enough leadership participation', 7),
('Unwilling to admit mistakes and learn from delivery failure', 7),
('Transformation is led by the technology organization', 7),
("Don't know", 7),
('None', 7),
('Other', 7),
# M11
('Average', 8),
('Never', 8),
('< 1 year', 8),
('1 - 2 years', 8),
('3 - 4 years', 8),
('> 5 years', 8),
# M12
('Project/Program Manager', 9),
('Consultant/Trainer', 9),
('Development Leadership', 9),
('Development Team', 9),
('IT Staff', 9),
('C-Level', 9),
('Scrum Master or Internal Coach', 9),
('Product Manager/Product Owner', 9),
('Business Analyst', 9),
('DevOps', 9),
('Portfolio Manager', 9),
('Other', 9),
# M14
('Yes', 10),
('No', 10),
# M15
('Sprint/Iteration Planning', 11),
('Unit Testing', 11),
('Daily Standup', 11),
('Release Planning', 11),
('Continuous Integration', 11),
('Retrospectives', 11),
('Refactoring', 11),
('Velocity', 11),
('Test-Driven Development (TDD)', 11),
('Common work area', 11),
('Collective Code Ownership', 11),
('Taskboard Combined', 11),
('On-site Customer', 11),
('Pair Programming', 11),
('Automated Builds', 11),
('Burndown/Team-Based Estimation/Planning Poker', 11),
('Coding Standards', 11),
('Digital Taskboard', 11),
('Analog Taskboard', 11),
('Behaviour Driven Development', 11),
('Kanban', 11),
('Automated Acceptance Testing', 11),
('Continuous Deployment', 11),
('Cycle Time', 11),
('Story Mapping', 11),
('Agile Games', 11),
('Dedicated Product Owner', 11),
('Integrated Dev/QA (Single Team)', 11),
('Short Iterations', 11),
('Prioritized Backlogs', 11),
('Sprint/Iteration Reviews', 11),
('Taskboard', 11),
('Frequent Releases', 11),
('Product Roadmapping', 11),
('Agile Portfolio planning', 11),
('Agile/Lean UX', 11),
('Other', 11),
# M16
('Microsoft Excel', 12),
('Microsoft Project', 12),
('Digital.ai Agility', 12),
('In-House/Homegrown', 12),
('Atlassian Jira', 12),
('Bugzilla', 12),
('Rational ', 12),
('XPlanner', 12),
('Primavera', 12),
('ThoughtWorks Mingle', 12),
('Target Process', 12),
('CollabNet', 12),
('Sapient ResultSpace', 12),
('Microsoft TFS', 12),
('Google Docs', 12),
('HP Quality Center', 12),
('IBM ClearCase', 12),
('IBM Rational Team Concert', 12),
('Pivotal Tracker', 12),
('LeanKit', 12),
('CA Agile Vision', 12),
('CA Clarity Agile', 12),
('HP Agile Manager', 12),
('Axosoft', 12),
('Hansoft', 12),
('Rally', 12),
('CollabNet ScrumWorks Pro', 12),
('CollabNet TeamForge', 12),
('Microsoft Azure DevOps', 12),
('Atlassian Jira Align', 12),
('Mural/Miro', 12),
('iObeya', 12),
('Aptio', 12),
('Trello', 12),
('Not specified', 12),
('No tools at all', 12),
('Other', 12),
# M18
('Company philosophy or culture at odds with core agile values', 13),
('Lack of experience with Agile methods', 13),
('External pressure to follow traditional waterfall phases and practices', 13),
('Unwillingness of the team', 13),
('Lack of cultural transition', 13),
('Lack of management support', 13),
('Insufficient training', 13),
('New to Agile', 13),
('Lack of understanding of broader organizational change required', 13),
('Lack of mutual trust between business and development', 13),
('A broader organizational or communications problem', 13),
('Inconsistent agile practices and processes', 13),
('Inefficient management collaboration', 13),
('Inability to continuously prioritize work', 13),
('Innefective collaboration', 13),
('Pressure to change things', 13),
('Not enough agile coaches', 13),
('Leader/sponsor no longer with the company', 13),
('None of our Agile projects failed', 13),
('Other', 13),
("Don't know", 13),
# M24
('Yes', 14),
('No', 14),
("Don't know", 14),
# M26 - ferramentas que já utiliza
('Wiki', 15),
('Index Cards', 15),
('Agile Project Management Tool', 15),
('Spreadsheet', 15),
('Bug Tracker', 15),
('Traditional Project Management Tool', 15),
('Unit Test Tool', 15),
('Automated Acceptance Test Tool', 15),
('Refactoring Tool', 15),
('Taskboard', 15),
('Requirements Management Tool', 15),
('Continuous Integration Tool', 15),
('Automated Build Tool', 15),
('Kanban Board', 15),
('Release Management Tool', 15),
('Story Mapping', 15),
('PPM Tool', 15),
('Ideas Management Tool', 15),
('Wireframes', 15),
('Product Roadmapping', 15),
('Static Analysis', 15),
('Timecards', 15),
# M26 - ferramentas que planeja utilizar
('Wiki', 16),
('Index Cards', 16),
('Agile Project Management Tool', 16),
('Spreadsheet', 16),
('Bug Tracker', 16),
('Traditional Project Management Tool', 16),
('Unit Test Tool', 16),
('Automated Acceptance Test Tool', 16),
('Refactoring Tool', 16),
('Taskboard', 16),
('Requirements Management Tool', 16),
('Continuous Integration Tool', 16),
('Automated Build Tool', 16),
('Kanban Board', 16),
('Release Management Tool', 16),
('Story Mapping', 16),
('PPM Tool', 16),
('Ideas Management Tool', 16),
('Wireframes', 16),
('Product Roadmapping', 16),
('Static Analysis', 16),
('Timecards', 16),
# M36
('> 1000', 17),
('> 5000', 17),
('< 1000', 17),
('1001 - 5000', 17),
('5001 - 20000', 17),
('> 20001', 17),
# M37
('Technology', 18),
('Financial Services', 18),
('Professional Services', 18),
('Healthcare/Pharmaceuticals', 18),
('Government', 18),
('Industrial/Manufacturing', 18),
('Telecommunications', 18),
('Retail', 18),
('Media/Entertainment', 18),
('Internet Services', 18),
('Insurance', 18),
('Transportation', 18),
('Consumer Products', 18),
('Utilities', 18),
('Public Services', 18),
('Education', 18),
('Energy', 18),
('Non-profit', 18),
('Other', 18),
# M38
('None of our teams are Agile', 19),
('Less than half of our teams are agile', 19),
('More than half of our teams are agile', 19),
('All of our teams are Agile', 19),
# M39
('No Agile initiatives', 20),
('Experimenting with Agile in pockets', 20),
('Teams ranging from very early to mature adoption', 20),
('Teams with mature adoption', 20),
('Had unsuccessful adoptions', 20),
('Agile practices are enabling greater adaptability', 20),
('High level of competency with Agile practices across the organization', 20),
('Use Agile practices but still maturing', 20),
('Considering an Agile initiative', 20),
# M40
('On-time delivery', 21),
('Product quality', 21),
('Customer/user satisfaction', 21),
('Business value', 21),
('Product scope', 21),
('Project visibility', 21),
('Productivity', 21),
('Predictability', 21),
('Process improvement', 21),
('Business objectives achieved', 21),
('Organizational culture/morale', 21),
("Don't know", 21),
('Other', 21),
# M41
('Velocity', 22),
('Iteration burndown', 22),
('Release burndown', 22),
('Planned vs. actual stories per iteration', 22),
('Burn-up chart', 22),
('Planned vs. actual release dates', 22),
('Customer/user satisfaction', 22),
('Work-in-Progress (WIP)', 22),
('Defects into production', 22),
('Defects over time', 22),
('Budget vs. actual cost', 22),
('Defect resolution', 22),
('Estimation accuracy', 22),
('Business value delivered', 22),
('Individual hours per iteration/week', 22),
('Cycle time', 22),
('Test pass/fail over time', 22),
('Scope change in a release', 22),
('Cumulative flow chart', 22),
('Earned value', 22),
('Customer retention', 22),
('Revenue/sales impact', 22),
('Product utilization', 22),
('Team morale', 22),
# M42
('Scrum/Scrum of Scrums', 23),
('Internally created methods', 23),
('Scaled Agile Framework (SAFe)', 23),
('Lean management', 23),
('Enterprise Agile', 23),
('Enterprise Scrum', 23),
('Agile Portfolio Management (APM)', 23),
('Disciplined Agile (DA)', 23),
('Large-Scale Scrum (LeSS)', 23),
('Recipes for Agile Governance in the Enterprise (RAGE)', 23),
('Nexus', 23),
('Spotify Model', 23),
("Don't know/Other", 23),
# M44
('Unit testing', 24),
('Continuous integration', 24),
('Coding standards', 24),
('Refactoring', 24),
('Test-driven deployment (TDD)', 24),
('Automated acceptance testing', 24),
('Continuous deployment', 24),
('Pair programming', 24),
('Sustainable pace', 24),
('Collective code ownership', 24),
('Behavior-driven development (BDD)', 24),
('Emergent design', 24),
('Continuous delivery', 24),
# M45
('DevOps initiative currently underway', 25),
('Planning a DevOps initiative', 25),
('No DevOps initiatives', 25),
("Don't know", 25),
# M46
('Not important', 26),
('Somewhat important', 26),
('Important', 26),
('Very important', 26),
# M47
('Accelerated delivery speed', 27),
('Improved quality', 27),
('Increased visibility of flow of value to users', 27),
('Reduce risk', 27),
('Increase customer satisfaction', 27),
('Decreased IT costs', 27),
('Ensure compliance/governance', 27),
('Delivery aligned with business objectives', 27),
('Improved relationship between Dev ond Ops', 27),
('Other', 27);